server:
  port: 8084 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyid: LTAI5tKGpduCuytwkXedDMj8
    keysecret: 82VGwb4ePS4nBur5L3ZAcNWaXqvQM5
#    keyid: LTAI5tKGpduCuytwkXedDMj8
#    keysecret: 82VGwb4ePS4nBur5L3ZAcNWaXqvQM5
    templateGroupId: 238858a3502d7dbbee9be37d5edf164f #转码模板组id 238858a3502d7dbbee9be37d5edf164f
    workflowId: 677e3d98b533f8aaab599fcd19dc1b5b #工作流id